### ISSUE TITLE
Random.nextInt(..) in Kotlin is not instrumented in the model checking mode

### ISSUE THREAD

**Issue by ndkoval** [JetBrains/lincheck#134]

**Comment by FenstonSingel** [comment]
@ndkoval This seems to be the issue that have been rediscovered for [`ThreadLocalRandom.nextInt(origin, bound)`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadLocalRandom.html#nextInt-int-int-) during May'23 Cyprus concurrent programming intensive course.

**Comment by ndkoval** [comment]
These two are different issues, but quite similar. Thanks for pointing that out!

**Comment by ndkoval** [comment]
Will be fixed under #285
