### ISSUE TITLE
Slf4j incompatibility

### ISSUE THREAD

**Issue by CLOVIS-AI** [JetBrains/lincheck#169]
When running a test which uses Slf4J's `LoggerFactory.getLogger`, the test fails (in both stress-testing and model-testing) with:

```
java.lang.reflect.InvocationTargetException
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl could not be instantiated: java.lang.ClassCastException: com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl cannot be cast to javax.xml.parsers.SAXParserFactory
Caused by: java.lang.ClassCastException: com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl cannot be cast to javax.xml.parsers.SAXParserFactory
```

[Full stack trace](https://opensavvy.gitlab.io/-/pedestal/-/jobs/4158494877/artifacts/test-report-cache/test/classes/opensavvy.cache.MemoryCacheLinearizationTest.html) | [Source commit](https://gitlab.com/opensavvy/pedestal/-/commit/1c5c820fd8f726dafd692332d7eaa6e44a93d8a7).

<details><summary>Full reproduction</summary>
<p>

Scripted as a Dockerfile for ease of use, but should do the same with any Java installation:

```dockerfile
FROM archlinux:base

# Requires a working JRE
RUN pacman -Syuu --noconfirm git jre-openjdk
ENV JAVA_HOME=/usr/lib/jvm/default-runtime

# Checkout the project
RUN mkdir -p /opt
RUN git clone https://gitlab.com/opensavvy/pedestal.git /opt/pedestal
WORKDIR /opt/pedestal
RUN git switch --detach 1c5c820f

# Run the JVM tests
RUN ./gradlew cache:jvmTest
```

</p>
</details> 

It seems a common pattern that Lincheck fails with logging libraries (#133, #116), but the error message is quite different, so I don't know if it's the same underlying problem or not.

**Comment by ndkoval** [comment]
The issue will likely be automatically resolved with #136

**Comment by CLOVIS-AI** [comment]
Hi! Indeed, it seems to work, now.

Well, at least, it runs, takes some time, and then ends without printing any errors. Can you take a quick look at [the test](https://gitlab.com/opensavvy/groundwork/pedestal/-/merge_requests/133/diffs) in case I wrote it incorrectly :pray:?

**Comment by ndkoval** [comment]
@CLOVIS-AI, the test looks good to me!

Since the issue has been fixed, I'm closing it now.
