### ISSUE TITLE
Hang in FixedActiveThreadsExecutor (Lincheck 2.19)

### ISSUE THREAD

**Issue by ben-manes** [JetBrains/lincheck#194]
When running on 2.18.1 a [github action](https://github.com/ben-manes/caffeine/actions/runs/5300645021/jobs/9594324647) takes 8 minutes to run the tests. When upgrading, it is still [running](https://github.com/ben-manes/caffeine/actions/runs/5306807313/jobs/9604830438) after 58 minutes. When running locally the tests complete without an error. I'll revert that upgrade to isolate it, but the other changes were benign code readability changes to please a static analyzer. So for now this is an fyi as I try to reproduce locally.

It canceled after a 60 minute timeout trying to verify an embedded copy of JCTools' `MpscGrowableArrayQueue`.

```
Gradle suite > Gradle test > com.github.benmanes.caffeine.cache.MpscGrowableArrayQueueLincheckTest > modelCheckingTest STARTED

Gradle suite > Gradle test > com.github.benmanes.caffeine.cache.MpscGrowableArrayQueueLincheckTest > stressTest STARTED
```

**Comment by ben-manes** [comment]
It ran fine when [downgrading](https://github.com/ben-manes/caffeine/actions/runs/5307320733/jobs/9605810561) to 2.18.1. Since it appears to [hang](https://github.com/ben-manes/caffeine/actions/runs/5307428313/jobs/9606023745) on 2.19, I probably need to ssh into it and run jstack or capture a jfr profile.

**Comment by ben-manes** [comment]
```console
"Test worker" #1 prio=5 os_prio=0 cpu=99787.06ms elapsed=202.38s tid=0x00007f8a7002c800 nid=0x8ea waiting on condition  [0x00007f8a74f14000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.19/Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.19/LockSupport.java:357)
        at org.jetbrains.kotlinx.lincheck.runner.FixedActiveThreadsExecutor.getResult(FixedActiveThreadsExecutor.kt:112)
        at org.jetbrains.kotlinx.lincheck.runner.FixedActiveThreadsExecutor.awaitTask(FixedActiveThreadsExecutor.kt:93)
        at org.jetbrains.kotlinx.lincheck.runner.FixedActiveThreadsExecutor.await(FixedActiveThreadsExecutor.kt:89)
        at org.jetbrains.kotlinx.lincheck.runner.FixedActiveThreadsExecutor.submitAndAwait(FixedActiveThreadsExecutor.kt:67)
        at org.jetbrains.kotlinx.lincheck.runner.ParallelThreadsRunner.run(ParallelThreadsRunner.kt:246)
        at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.runInvocation(ManagedStrategy.kt:226)
        at org.jetbrains.kotlinx.lincheck.strategy.managed.modelchecking.ModelCheckingStrategy.runImpl(ModelCheckingStrategy.kt:62)
        at org.jetbrains.kotlinx.lincheck.strategy.managed.ManagedStrategy.run(ManagedStrategy.kt:121)
        at org.jetbrains.kotlinx.lincheck.LinChecker.run(LinChecker.kt:142)
        at org.jetbrains.kotlinx.lincheck.LinChecker.checkImpl(LinChecker.kt:75)
        at org.jetbrains.kotlinx.lincheck.LinChecker.checkImpl$lincheck(LinChecker.kt:47)
        at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.kt:37)
        at com.github.benmanes.caffeine.cache.MpscGrowableArrayQueueLincheckTest.modelCheckingTest(MpscGrowableArrayQueueLincheckTest.java:69)
```

I believe in https://github.com/JetBrains/lincheck/issues/130#issuecomment-1328312270 I found that the framework swallows all throwables and retries, so that could mean this is timing out but never completing.

**Comment by ndkoval** [comment]
Hi @ben-manes, could you please fix whether the issue is resolved in 2.20?

**Comment by ben-manes** [comment]
It's not looking great so far at 30 minutes ([job](https://github.com/ben-manes/caffeine/actions/runs/5426917127/jobs/9869708493)) (vs 8 minutes).

**Comment by ndkoval** [comment]
I guess Lincheck 2.19+ works badly when the number of cores exceeds the number of threads. Is it the case here?

**Comment by ben-manes** [comment]
I'd have thought the opposite? It runs fine on my old macbook (8 ht cores) but fails on github actions ([2 core](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)). This hung on the [model checker](https://github.com/ben-manes/caffeine/blob/56660754ecca83ff25c192f905871c252dd2630f/caffeine/src/test/java/com/github/benmanes/caffeine/cache/MpscGrowableArrayQueueLincheckTest.java#L65) where I did not override the `threads` option, which looks to be 2.

**Comment by ndkoval** [comment]
@ben-manes, could you please check whether the fix #204 in Lincheck 2.21 solves the issue?

**Comment by ben-manes** [comment]
kicked off on [x86](https://github.com/ben-manes/caffeine/actions/runs/5449096430) and [arm64](https://app.circleci.com/pipelines/github/ben-manes/caffeine/1909/workflows/9d367924-8a77-493c-80d6-d8f85d71a893)

**Comment by ben-manes** [comment]
no luck, 45min in so should timeout soon

**Comment by ben-manes** [comment]
I tried adjusting `Runtime.getRuntime().availableProcessors()` to a synthetic value by using `-XX:ActiveProcessorCount`, hoping to reproduce it locally or fix it remotely. Unfortunately that didn't work. I had thought maybe if it was core vs thread counts that might trick it, but it may be something else.

**Comment by ndkoval** [comment]
@ben-manes, is it possible to get a thread dump?

**Comment by ben-manes** [comment]
The jfr recording linked above includes a thread dump. I can try to capture a new one on the latest version if that helps, but will may have to wait until the weekend. I believe that I used [action-upterm](https://github.com/lhotari/action-upterm) to ssh into the action before it ran the [lincheckTest](https://github.com/ben-manes/caffeine/blob/b2dc82ddc8d8ba3c6566e7c1bdef9742f12f52a6/.github/workflows/build.yml#L131C22-L131C34) suite.

If you wanted to try to iterate on a bug fix, the approach that I would take is to make a reproducer repository that is trimmed to just the work needed, switch the lincheck dependency to jitpack and use a commit hash version, ssh as needed, and iterate until the cause is figured out.

**Comment by ben-manes** [comment]
I trimmed the build, added upterm, and ran the following on the host. The jfr and stacktrace files are attached. The profile recording has per-minute thread dumps and additional information.

```
touch continue

export LINCHECK=$(jps | grep GradleWorkerMain | cut -f1 -d' ')
echo $LINCHECK

jcmd $LINCHECK JFR.start duration=15m filename=/home/runner/work/caffeine/caffeine/lincheck.jfr settings=profile.jfc
sleep 960 && echo -ne '\007'
jcmd $LINCHECK JFR.check

zip lincheck lincheck.jfr
curl -s -F "file=@lincheck.zip" https://file.io | jq -r '.link'

jstack $LINCHECK > stacktrace.txt
curl -s -F "file=@stacktrace.txt" https://file.io | jq -r '.link'
```

[lincheck.zip](https://github.com/JetBrains/lincheck/files/12060530/lincheck.zip)
[stacktrace.txt](https://github.com/JetBrains/lincheck/files/12060531/stacktrace.txt)

**Comment by ben-manes** [comment]
still no luck as of 2.23 ([build](https://github.com/ben-manes/caffeine/actions/runs/5723280775/job/15507803658))

**Comment by ben-manes** [comment]
Anything more that you need? I’m fine pinning to the old version but it’s a bit concerning of a regression and might confuse new users.

**Comment by ndkoval** [comment]
Hi, @ben-manes! Sorry for the very long reply. Could you please check whether the issue still reproduces in Lincheck 2.25?

**Comment by ben-manes** [comment]
works for me!
