### ISSUE TITLE
Threads are not killed after completing tests with deadlocks found with locks

### ISSUE THREAD

**Issue by avpotapov00** [JetBrains/lincheck#199]
When running all tests suite, after test `DeadlockOnSynchronizedTest` passed, we observe increased number of threads in the system. (see picture and dump from TeamCity)
<img width="304" alt="image" src="https://github.com/JetBrains/lincheck/assets/45040429/311ef487-7e4a-4559-bca7-c556799421ac">
[dump.txt](https://github.com/JetBrains/lincheck/files/11905138/dump.txt)

**Comment by avpotapov00** [comment]
As a result, after test with deadlocks on `synchronized` we have many threads in BLOCKING state, holding resources and slowing down further execution.

**Comment by ndkoval** [comment]
@avpotapov00, would `ThreadDeath` interrupt the thread if it were parked via `LockSupport.part()`?

**Comment by ndkoval** [comment]
We can't do much about that. As #214 mentions, a possible solution for us would be to run such "bad" tests (that produce hanging threads) in separate VMs.
