### ISSUE TITLE
Lincheck tests are slow when the number of CPUs is lower than the number of parallel threads

### ISSUE THREAD

**Issue by ndkoval** [JetBrains/lincheck#280]
Please see https://github.com/JetBrains/lincheck/issues/278#issuecomment-1953512719 for details:
> It seems to have [hung](https://app.circleci.com/pipelines/github/ben-manes/caffeine/2855/workflows/f69f4a38-26d4-4a24-bd43-964516299e24/jobs/71526) on aarch64.
>
> I have run it successfully locally on an M3 macbook, but not on CircleCI, likely because of fewer cpu cores (as we saw that affected Lincheck in past bugs).

**Comment by ben-manes** [comment]
Thanks, working beautifully now!

**Comment by ben-manes** [comment]
was there a regression? I tried to upgrade 2.27 to 2.28.x and it times out ([2.28](https://app.circleci.com/pipelines/github/ben-manes/caffeine/3025/workflows/5adff2ee-9902-4555-a56e-8a4240a1f162/jobs/76742/parallel-runs/0/steps/0-114), [2.28.1](https://app.circleci.com/pipelines/github/ben-manes/caffeine/3022/workflows/5977230b-b865-4e7a-a1ed-5c150a5fc176/jobs/76632)) like before.

**Comment by eupp** [comment]
Hi @ben-manes !
Yes, this is probably a regression. I'll take a look at it. 
Could you please pin the version 2.27 for now?

**Comment by ben-manes** [comment]
thanks @eupp! Please consider adding a test case.
