### ISSUE TITLE
Bug in the minimization of the initial part of a scenario

### ISSUE THREAD

**Issue by eupp** [JetBrains/lincheck#286]
Apparently, there is a bug in the scenario minimization, related to the minimization of initial part of a scenario.
It leads to flaky tests. See examples in these builds on CI: [1](https://teamcity.jetbrains.com/buildConfiguration/KotlinTools_KotlinxLincheck_BuildLinuxOnJava21/4512433), [2](https://teamcity.jetbrains.com/buildConfiguration/KotlinTools_KotlinxLincheck_BuildLinuxOnJava15/4511992), [3](https://teamcity.jetbrains.com/buildConfiguration/KotlinTools_KotlinxLincheck_BuildMacOnJava17/4499504)

**Comment by ndkoval** [comment]
@eupp should incrementing the number of invocations help?

**Comment by eupp** [comment]
> should incrementing the number of invocations help?
Maybe this happens because of the small number of invocations, indeed. Let's try to increase the number and see.
