### ISSUE TITLE
Names of variables that are written/read through AtomicReference are not displayed in trace

### ISSUE THREAD

**Issue by avpotapov00** [JetBrains/lincheck#317]
As the AtomicReference doesn't receive a string name of a variable to read/write it, Lincheck currently can't provide its name. The goal is to fix it.

**Comment by ndkoval** [comment]
To determine the related field, you can analyze the tested object and find all the fields referencing the specified `AtomicReference` (or `AtomicInteger`, `AtomicLong`, etc) instance. In case there is only one such reference, you can safely present the field name.

Thus, instead of 
```
get()
```
you will print
```
Node#1.id.get()
```
