### ISSUE TITLE
Object numeration doesn't correspond between plugin and text output

### ISSUE THREAD

**Issue by avpotapov00** [JetBrains/lincheck#343]
Consider the following example and the comments in the code:

```kotlin
class MyTest {
    private var ref1 = Node(1)
    private var ref2: Node? = null
    private var c: Int = 0

    fun increment(): Int {
        // When the plugin is enabled, before this instruction  method`org.jetbrains.kotlinx.lincheck.IdeaPluginKt.visualize` is called,
        // and it will recursively traverse all the MyTest instance to enumerate objects and find out ref1 -> Node(1) object, so it would have number 1.
        // when plugin is disabled, we won't even consider this object as it hasn't been involved in the execution yet.
        c++
        // Here, when the plugin is enabled, in `beforeWriteField` we'll give `Node(0)` object number 2, as 
        // we already have seen an object of type `Node`. When the plugin is disabled, this object will be the 
        // first instance of `Node` type and will get the number 1.
        ref2 = Node(0)
        return c
    }

    @Test
    fun test() = ModelCheckingOptions()
        .addCustomScenario {
            parallel {
                thread { actor(::increment) }
                thread { actor(::increment) }
            }
        }.check(this::class)

    class Node(val value: Int)

}
```

So, generally, the problem is that when the Plugin is enabled, we may see some objects before they appear in the trace. Therefore, a smaller number will be assigned to them, and a bigger number will be assigned to the next object of the same type in the trace.

**Comment by avpotapov00** [comment]
Let's consider when it may happen. 
For this to happen, some objects must be created, and we must want to visualize them but not appear in the trace yet.
For now, we want to visualize all objects accessible from the tested object (but later, we may wish to visualize objects on the stack, so we have to keep that in mind!).
There are two ways for an object to become accessible from the tested object:
1. To be written somehow into the field during the execution (not in the constructor).
2. To be written into the field in the constructor `<init>`.

In most of the (1) cases, we really process this object in the trace collection so it won't cause this bug. 
But (2) case clearly breaks our numeration because we wrap all `<init>` methods in the ignored section, so this object creation won't be in the trace, so the numeration will be broken.

**Comment by avpotapov00** [comment]
The most straightforward and obvious way to solve this is to call enumerate objects on every step during trace collection, even if the plugin is not enabled. 
It won't affect performance in any considerable way (as in the plugin, we do absolutely the same, and it's OK), and the numeration is going to be the same in both cases (with the Plugin and without).

**Comment by avpotapov00** [comment]
@ndkoval what do you think?

**Comment by ndkoval** [comment]
@avpotapov00, thanks for the investigation! Let's go ahead with your plan.

**Comment by eupp** [comment]
Resolved by https://github.com/JetBrains/lincheck/pull/702
