### ISSUE TITLE
Provide a DSL to declare algorithms

### ISSUE THREAD

**Issue by CLOVIS-AI** [JetBrains/lincheck#359]
Instead of writing
```kotlin
class CounterTest {
    private val c = Counter() // Initial state

    // Operations on the Counter
    @Operation
    fun inc() = c.inc()

    @Operation
    fun get() = c.get()

    @Test // Run the test
    fun stressTest() = StressOptions().check(this::class)
}
```

I would prefer to write
```kotlin
val model = lincheckModel {
    private val c = Counter() // Initial state

    operation("inc") {
        c.inc()
    }

    operation("get") {
        c.get()
    }
}

class CounterTest {
    @Test // Run the test
    fun stressTest() = StressOptions().check(model)
}
```
(or a similar DSL).

The usage of a DSL would:
- Make tests more IDE-friendly (autocomplete showing the different functions, instead of annotations)
- Make the library compatible with DSL-based test frameworks, such as [Kotest](https://github.com/kotest/kotest) or [Prepared](https://opensavvy.gitlab.io/groundwork/prepared/docs/)
- Make models more flexible: allow using loops, creating builders, …

***

My main use-case is that I have multiple cache algorithms. They all have a common interface, and all have the exact same operations. I want to test all of them with Lincheck. With this DSL implemented, and using a DSL-based test framework (Prepared in this example):
```kotlin
fun SuiteDsl.lincheck(algorithm: Prepared<Cache<Int, Int>>) {
    val model by prepared {
        val algorithm = algorithm()
        lincheckModel {
            operation("get") { it: Int -> algorithm[it] }
            operation("expire") { it: Int -> algorithm.expire(it) }
            operation("clear") { algorithm.clear() }
        }
    }

    test("Stress testing") {
        StressOptions().check(model())
    }

    test("Model checking") {
        ModelCheckingOptions().check(model())
    }
}
```

Currently, without this feature, the only way is to duplicate the entire test class for each implementation.

**Comment by ndkoval** [comment]
Hi @CLOVIS-AI! Thanks for raising this issue. We are now working on a new API for Lincheck. 

Meanwhile, I would suggest leveraging inheritance to avoid code duplication -- take a look at how we test different channels in Kotlin coroutines: https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/jvm/test/lincheck/ChannelsLincheckTest.kt#L18

**Comment by CLOVIS-AI** [comment]
Thanks. Is there a place to follow the work on the new API? I'd like to follow development, if possible.

**Comment by ndkoval** [comment]
@CLOVIS-AI, we will create an issue with the API design when we have a preliminary version.

**Comment by CLOVIS-AI** [comment]
Hi If anyone is still following this thread, it looks like this has been implemented in 3.0: https://github.com/JetBrains/lincheck/blob/master/README.md#2-write-your-first-lincheck-test

**Comment by eupp** [comment]
Hi @CLOVIS-AI 

In Lincheck-3.0 we added a new API: `Lincheck.runConcurrentTest { ... }` which allows to test under model checker (almost) arbitrary code, supplied in the lambda.

But this is a bit different API for a different use-case. 
For data structures testing it still possible to use old API. 

At some point we were also discussing an implementation of a new more "modern" API for data structures, but that work was postponed in favor of other stuff. However, if there is an interest from the community in this direction, we can raise the priority of this task.

What would you like to see from a potential new data structures API?
What are you pain points regarding current API shape?

**Comment by CLOVIS-AI** [comment]
> What are you pain points regarding current API shape?

Purely that operations cannot be declared dynamically, they have to be methods annotated with `@Operation`. 

As part of Prepared, I aim to offer a single unified DSL for multiple testing styles, allowing all of them to be combined: parameterization, concurrency testing, benchmarks, contract testing,… I'm confident the authors of Kotest and TestBalloon have the same goals.

To allow such testing libraries to interoperate well with our frameworks, our frameworks need to be able to declare the tests dynamically.

For example, if Lincheck provided a simple
```kotlin
StressOptions().check(
    ModelBuilder()
        .withOperation("foo") { … }
        .withOperation("bar") { … }
        .build()
)
```
that would be enough for my needs. This API doesn't need to be the primary way with which Lincheck users interact with the library, and maybe the annotation-based syntax could delegate to it internally, it just needs to exist so that other libraries can build upon it.
